"""add role and establishment_id to usuarios

Revision ID: 31e41ad995a0
Revises: c81609cbe2c4
Create Date: 2025-09-17 11:42:47.899194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e41ad995a0'
down_revision: Union[str, None] = 'c81609cbe2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('role', sa.Enum('user', 'owner', 'employee', name='role'), nullable=True))
    op.add_column('usuarios', sa.Column('establishment_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios') as batch_op:
        batch_op.drop_constraint('fk_usuarios_establishment_id', type_='foreignkey')
        batch_op.drop_column('establishment_id')
        batch_op.drop_column('role')
    # ### end Alembic commands ###
