"""add_missing_fields

Revision ID: 3fbd34cbb378
Revises: 31e41ad995a0
Create Date: 2025-09-17 14:16:21.857522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fbd34cbb378'
down_revision: Union[str, None] = '31e41ad995a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios') as batch_op:
        batch_op.create_foreign_key('fk_usuarios_establishment_id', 'estabelecimentos', ['establishment_id'], ['id'])

    op.add_column('usuarios_na_fila', sa.Column('prioridade', sa.Enum('normal', 'high', name='priority'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios_na_fila', 'prioridade')
    with op.batch_alter_table('usuarios') as batch_op:
        batch_op.drop_constraint('fk_usuarios_establishment_id', type_='foreignkey')
    # ### end Alembic commands ###
